competition/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

urlpatterns = patterns('',
	# Things every user will see
    url(r'^$', 'competition.views.home', name='home'),
    url(r'^updates/$', 'competition.views.updates', name='updates'),
    url(r'^info/$', 'competition.views.info', name='info'),
    
    # User management URLs
    url(r'^signin/$', 'competition.views.signin', name='signin'),
    url(r'^create/$', 'competition.views.createaccount', name='createaccount'),
    url(r'^delete/$', 'competition.views.auth_delete', name='delete'),
    url(r'^logout/$', 'competition.views.auth_logout', name='logout'),
    url(r'^password/$', 'competition.views.resetpassword', name='password'),
    url(r'^newpassword/$', 'competition.views.newpassword', name='newpassword'),
    
    # Admin-specific things
    url(r'^participants/$', 'competition.views.participants', name='participants'),
    url(r'^createupdate/$', 'competition.views.createupdate', name='createupdate'),
)

mathcomp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import views

urlpatterns = patterns('',
    url(r'^$', 'mathcomp.views.home', name='home'),
    url(r'^competition/', include('competition.urls', namespace='competition')),
    
    url(r'^admin/', include(admin.site.urls)),
)

competition/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.
class SiteUserManager(BaseUserManager):
	def _create_user(self, email, password, first_name=None, last_name=None, department=None, school=None, lab=None, pi=None, research_interest=None, **extra_fields):
		if not email:
			raise ValueError('An email must be provided to create the user.')
		email = self.normalize_email(email)
		user = self.model(email=email)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, email, password, first_name=None, last_name=None, department=None, school=None, lab=None, pi=None, research_interest=None, **extra_fields):
		return self._create_user(email, password)

	def create_superuser(self, email, password, first_name=None, last_name=None, department=None, school=None, lab=None, pi=None, research_interest=None, **extra_fields):
		return self._create_user(email, password)

	def get_by_natural_key(self, username):
		""" Allow Case-Insensitive Username. """
		return self.get(email__iexact=username)

class SiteUser(AbstractBaseUser):
	email = models.EmailField('email address', max_length=200, unique=True,
		error_messages={
			'unique': 'A user with that email already exists.',
		}, help_text="Emory Email Address")
	first_name = models.CharField(max_length=100, help_text="First Name")
	last_name = models.CharField(max_length=100, help_text="Last Name")
	
	is_staff = models.BooleanField(default=False)
	
	objects = SiteUserManager()

	# Required for custom user model
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	def get_full_name(self):
		return self.first_name, self.last_name

	def get_short_name(self):
		return self.first_name
	
	email = models.EmailField('email address', max_length=200, unique=True,
		error_messages={
			'unique': 'A user with that email already exists.',
		}, help_text="Email Address")

class Announcement(models.Model):
	title = models.CharField(max_length=100)
	message = models.TextField(max_length=10000)
	created_at = models.DateTimeField(auto_now_add=True, default=None)

class ResetPassword(models.Model):
	email = models.EmailField('email address', max_length=200)
	identifier = models.CharField(max_length=200)

competition/forms.py
from django import forms
from competition.models import *
from django.conf import settings

class LoginForm(forms.Form):
	''' On log in, you only need an email and a password '''
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

class SignupForm(forms.ModelForm):
	''' This is the main sign-up form '''
	error_messages = { # Add errors here
		'password_mismatch': 'The two password fields didn\'t match.',
        }
	# Form needs two passwords to make sure the user doesn't mistype
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control text-center', 'placeholder': 'Password'}), label='Password', help_text='Choose a password')
	retype_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control text-center', 'placeholder': 'Retype Password'}), label='Retype Password', help_text='Enter the same password as above, for verification.')

	class Meta:
		model = SiteUser
		
		# These are the fields that the user needs to input when they create their account
		fields = ('email', 'first_name', 'last_name')
		widgets = {
				'email': forms.EmailInput(attrs={'class': 'form-control text-center', 'placeholder': 'Email Address'}),
				'first_name': forms.TextInput(attrs={'class': 'form-control text-center', 'placeholder': 'First Name'}),
				'last_name': forms.TextInput(attrs={'class': 'form-control text-center', 'placeholder': 'Last Name'}),
		    }

	# This method validates that the two passwords are the same
	# If they don't match it throws an error
	def clean_retype_password(self):
		password = self.cleaned_data.get('password')
		retype_password = self.cleaned_data.get('retype_password')
		if password and retype_password and password != retype_password:
			raise forms.ValidationError(
				self.error_messages['password_mismatch'],
				code='password_mismatch',
			    )
		return retype_password

	# This is the method for saving the newly created user
	def save(self, commit=True):
		user = super(SignupForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password'])
		if commit:
			user.save()
		return user

class GetPasswordReset(forms.ModelForm):
	class Meta:
		model = ResetPassword
		fields = ('email',)
		widgets = {
			'email': forms.TextInput(attrs={'class': 'form-control text-center', 'placeholder': 'Enter Email Address'}),
		}

class ResetPasswordForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control text-center', 'placeholder': 'Password'}), label='Password', help_text='Choose a password')
	retype_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control text-center', 'placeholder': 'Retype Password'}), label='Retype Password', help_text='Enter the same password as above, for verification.')
	
	def clean_retype_password(self):
		password = self.cleaned_data.get('password')
		retype_password = self.cleaned_data.get('retype_password')
		if password and retype_password and password != retype_password:
			raise forms.ValidationError(
				self.error_messages['password_mismatch'],
				code='password_mismatch',
			    )
		return retype_password
	
	def save(self, commit=True):
		user = super(SignupForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password'])
		if commit:
			user.save()
		return user

class UpdateForm(forms.ModelForm):
	class Meta:
		model = Announcement
		fields = ('title', 'message',)
		widgets = {
			'title': forms.TextInput(attrs={'placeholder': 'Title'}),
			'message': forms.Textarea(attrs={'placeholder': 'Message'}),
		}

competition/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login, logout, get_user
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from competition.forms import *

import random

def is_staff(user):
	return user.is_staff

def home(request):
	''' Home page '''
	context = {
		'current_page': 'home',
	}
	if request.user.is_authenticated():
		return render(request, 'competition_home.html', context)
	else:
		return render(request, 'competition_splash.html', context)

def newpassword(request):
	''' Set new password '''
	context = {}
	if request.POST:
		form = ResetPasswordForm(request.POST)
		if form.is_valid() and 'identifier' in request.POST:
			new_password = form.cleaned_data['password']
			reset_obj = ResetPassword.objects.get(identifier = request.POST['identifier'])
			users = SiteUser.objects.filter(email=reset_obj.email)
			if users.count():
				user = users.first()
				user.set_password(new_password)
				user.save()
				reset_obj.delete()
				return HttpResponseRedirect(reverse('competition:home'))
		context['message'] = 'Your password update failed.'
	elif 'id' in request.GET and ResetPassword.objects.filter(identifier=request.GET['id']).count():
		r = ResetPassword.objects.filter(identifier=request.GET['id'])
		form = ResetPasswordForm()
		context['id'] = request.GET['id']
		context['form'] = form
	else:
		context['message'] = 'Where did you get this url? You should go somewhere else.'
	return render(request, 'new_password.html', context)

def resetpassword(request):
	''' Reset your password '''
	context = {}
	if request.POST:
		form = GetPasswordReset(request.POST)
		if form.is_valid() and SiteUser.objects.filter(email=form.cleaned_data['email']).exists():
			random_hash = "%032x" % random.getrandbits(128) # Generate random hash for resetting password
			ResetPassword.objects.filter(email=form.cleaned_data['email']).delete() # Delete any old objects
			password_reset_object = ResetPassword.objects.create(email=form.cleaned_data['email'], identifier=random_hash) # Create new object
			password_reset_object.save()
			
			email_content = 'You have requested that your password be reset. The url to do this is '
			email_content = email_content + reverse('competition:newpassword') + '?id=' + random_hash
			
			email_address = str(form.cleaned_data['email'])
			
			''' Need to send the email address here '''
			
			context['message'] = 'Your password reset email has been sent.'
		else:
			context['message'] = 'Your email address was not found.'
	else:
		form = GetPasswordReset()
		context['message'] = 'Enter your email address to reset your password.'
	context['form'] = form
	return render(request, 'reset_password.html', context)

def info(request):
	''' Info '''
	context = {
		'current_page': 'info',
	}
	return render(request, 'competition_info.html', context)

@login_required
def updates(request):
	context = {
		'current_page': 'updates',
		'announcements': Announcement.objects.order_by('-created_at'),
	}
	return render(request, 'competition_updates.html', context)

@user_passes_test(is_staff)
def participants(request):
	context = {
		'current_page': 'participants',
	}
	context['all_competitors'] = SiteUser.objects.all()
	return render(request, 'competition_participants.html', context)

@user_passes_test(is_staff)
def createupdate(request):
	if request.POST:
		form = UpdateForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('competition:updates'))
	else:
		form = UpdateForm()
	context = {
		'current_page': 'createupdate',
		'form': form,
	}
	return render(request, 'competition_createupdate.html', context)

@login_required
def auth_delete(request):
	''' Delete an account '''
	context = {}
	user = SiteUser.objects.get(email=request.user.email)
	user.delete()
	return HttpResponseRedirect(reverse('competition:home'))

def signin(request):
	if request.POST:
		form = LoginForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			user = authenticate(email=email, password=password)
			if user:
				login(request, user)
				if request.GET.get('next', False):
					return HttpResponseRedirect(request.GET.get('next', False))
				else:
					return HttpResponseRedirect(reverse('competition:home'))
	else:
		form = LoginForm()
	context = {
		'pagetitle': 'Sign In',
		'title': 'Please sign in',
		'buttontext': 'Sign In',
		'form': form,
	}
	return render(request, 'login.html', context)

def createaccount(request):
	if request.POST:
		form = SignupForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			password = form.clean_retype_password()
			form.save()
			user = authenticate(email=email, password=password)
			login(request, user)
			return HttpResponseRedirect(reverse('competition:home'))
	else:
		form = SignupForm()
	context = {
		'pagetitle': 'Create Account',
		'title': 'Create an account',
		'buttontext': 'Create Account',
		'form': form,
	}
	return render(request, 'login.html', context)

def auth_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('competition:signin'))

competition/templates/competition_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>EUMMA Math Competition</title>
    
    {% load staticfiles %}
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head %}{% endblock %}
  </head>

  <body>
  	<!-- top navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'competition:home' %}">Dashboard</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          	<li><a href="{% url 'competition:home' %}">Home</a></li>
          	<li><a href="{% url 'competition:updates' %}">Updates</a></li>
            <li><a href="{% url 'competition:logout' %}">Log Out</a></li>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container-fluid">
      <div class="row">
    	<!-- side navbar -->
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li{% if current_page == 'home' %} class="active"{% endif %}><a href="{% url 'competition:home' %}">Home</a></li>
            <li{% if current_page == 'updates' %} class="active"{% endif %}><a href="{% url 'competition:updates' %}">Updates</a></li>
          </ul>
        {% if user.is_staff %}
          <ul class="nav nav-sidebar">
            <li{% if current_page == 'participants' %} class="active"{% endif %}><a href="{% url 'competition:participants' %}">Participant List</a></li>
            <li{% if current_page == 'createupdate' %} class="active"{% endif %}><a href="{% url 'competition:createupdate' %}">Add an Update</a></li>
          </ul>
        {% endif %}
        </div>
        
        <!-- body -->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block body %}{% endblock %}
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

competition/templates/competition_createupdate.html
{% extends 'competition_base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<h1>Create Update</h1>
      <form method="post">
      	{% csrf_token %}
        {% for field in form %}
        	<div style="padding-bottom: 10px;">
        	{{ field }}
        	</div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Create Update</button>
      </form>
{% endblock %}

competition/templates/competition_home.html
{% extends 'competition_base.html' %}

{% block head %}

{% endblock %}

{% block body %}
          <h1 class="page-header">Dashboard</h1>
          <p>You are now registered for the math competition. To remove your account, go <a href="{% url 'competition:delete' %}">here</a>.
          <p>Logged in as {{ user.first_name }} {{ user.last_name }}, {{ user }}</p>
{% endblock %}

competition/templates/competition_info.html
{% extends 'competition_base.html' %}

{% block head %}

{% endblock %}

{% block body %}
          <h1 class="page-header">Competition Information</h1>
          <p>This is the website for the upcoming math competition, hosted by the Emory Undergraduate Math and Computer Science Majors Association.</p>
          <p>To get more information about the event, including recent posts, <a href="{% url 'competition:createaccount' %}">create an account</a> or <a href="{% url 'competition:signin' %}">log in</a>.</p>
{% endblock %}

competition/templates/competition_participants.html
{% extends 'competition_base.html' %}

{% block head %}

{% endblock %}

{% block body %}
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email</th>
                </tr>
              </thead>
              <tbody>
              {% for competitor in all_competitors %}
              	<tr>
              		<td>{{ competitor.id }}</td>
              		<td>{{ competitor.first_name }}</td>
              		<td>{{ competitor.last_name }}</td>
              		<td>{{ competitor.email }}</td>
              	</tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
{% endblock %}

competition/templates/competition_splash.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>Emory Math Majors Association</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container form-signin">
    	<h2 class="form-signin-heading" style="text-align: center;">EUMMA Competition 2014</h2>
		<a class="btn btn-lg btn-primary btn-block" href="{% url 'competition:signin' %}">Log In</a>
		<a class="btn btn-lg btn-primary btn-block" href="{% url 'competition:createaccount' %}">Create Account</a>
		<a class="btn btn-lg btn-primary btn-block" href="{% url 'competition:info' %}">Information</a>
		<!-- Not yet ready... <a class="btn btn-lg btn-primary btn-block" href="{% url 'competition:password' %}">Reset Password</a> -->
		<a class="btn btn-lg btn-block" href="http://www.mathcs.emory.edu/">Emory Math/CS Website</a>
		<a class="btn btn-lg btn-block" href="http://www.students.emory.edu/EUMMA/">EUMMA Website</a>
		<a class="btn btn-lg btn-block" href="https://www.facebook.com/mathandcsemory?fref=ts">Facebook</a>
    </div> <!-- /container -->
  </body>
</html>

<!--
<html>
	<head>
		<title>EUMMA</title>
	</head>
	<body>
		<div style="width: 100%; height: 100%">
			<div style="max-width: 300px; margin: auto; text-align: center; padding-top: 100px;">
				<h1>EUMMA Math Competition 2014</h1>
				<div>
					<ul style="list-style-type: none; padding: 0; margin: 0;">
						<li><a href="{% url 'competition:signin' %}">Log In</a></li>
						<li><a href="{% url 'competition:createaccount' %}">Create an Account</a></li>
						<li><a href="http://www.mathcs.emory.edu/">Emory Math/CS Website</a></li>
						<li><a href="http://www.students.emory.edu/EUMMA/">EUMMA Website</a></li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html> -->

competition/templates/competition_updates.html
{% extends 'competition_base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<h1>Updates</h1>
{% for announcement in announcements %}
<h4>{{ announcement.title }}</h4>
<p><i>{{ announcement.created_at }}</i> {{ announcement.message }}</p>
{% endfor %}
{% endblock %}

competition/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>{{ pagetitle }}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container form-signin">

      <form method="post">
      	{% csrf_token %}
        <h2 class="form-signin-heading">{{ title }}</h2>
        {% for field in form %}
        	<label for="{{ field.id_for_label }}" class="sr-only">{{ field.label }}</label>
        	{{ field }}
        {% endfor %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">{{ buttontext }}</button>
      </form>
      	<div class="container-fluid" style="padding-top: 10px; text-align: center;">
	    	<a href="{% url 'home' %}">Home</a> |
	    	<a href="{% url 'competition:signin' %}">Sign In</a> |
	    	<a href="{% url 'competition:createaccount' %}">Create An Account</a>
		</div>
    </div> <!-- /container -->
  </body>
</html>

competition/templates/new_password.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>{{ pagetitle }}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container form-signin">
    {{ message }}
	{% if form %}
      <form method="post">
      	{% csrf_token %}
        <h2 class="form-signin-heading">{{ title }}</h2>
        <input type="hidden" name="identifier" value="{{ id }}"/>
        {% for field in form %}
        	<label for="{{ field.id_for_label }}" class="sr-only">{{ field.label }}</label>
        	{{ field }}
        {% endfor %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
      </form>
	{% endif %}
    </div> <!-- /container -->
  </body>
</html>

competition/templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>{{ pagetitle }}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container form-signin">
    {{ message }}
	{% if form %}
      <form method="post">
      	{% csrf_token %}
        <h2 class="form-signin-heading">{{ title }}</h2>
        {% for field in form %}
        	<label for="{{ field.id_for_label }}" class="sr-only">{{ field.label }}</label>
        	{{ field }}
        {% endfor %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
      </form>
      	<div class="container-fluid" style="padding-top: 10px; text-align: center;">
	    	<a href="{% url 'home' %}">Home</a> |
	    	<a href="{% url 'competition:signin' %}">Sign In</a> |
	    	<a href="{% url 'competition:createaccount' %}">Create An Account</a>
		</div>
	{% endif %}
    </div> <!-- /container -->
  </body>
</html>